version: 2.1
jobs:
  deps_api:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/apydox/api
    steps:
      - checkout:
          path: ~/apydox
      - run: go get -v -t -d ./...
      - save_cache:
          key: apydox-api-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/apydox/api
            - "/go/pkg"
  test_api:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/apydox/api
    steps:
      - restore_cache:
          keys:
            - apydox-api-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-api-v1-{{ .Branch }}-
            - apydox-api-v1-
      # Unfortunately couldn't seem to get this working with caching the binary dependencies,
      # so we have to install the global binary packages in the test job.
      - run: go get github.com/axw/gocov/gocov
      - run: go get github.com/AlekSi/gocov-xml
      - run: gocov test -v ./... | gocov-xml > coverage.xml || TEST_RUNNER_EXIT_CODE=$?
      - run: exit $TEST_RUNNER_EXIT_CODE
  deps_portal:
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    working_directory: ~/apydox/portal
    steps:
      - checkout:
          path: ~/apydox
      - run: yarn
      - run: cp src/content.example.json src/content.json
      - save_cache:
          key: apydox-portal-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/apydox/portal
  test_portal:
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    working_directory: ~/apydox/portal
    steps:
      - restore_cache:
          keys: 
            - apydox-portal-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-portal-v1-{{ .Branch }}-
            - apydox-portal-v1-
      - run: yarn test || TEST_RUNNER_EXIT_CODE=$?
      - run: yarn codacy-coverage
      - run: exit $TEST_RUNNER_EXIT_CODE
workflows:
  version: 2
  deps_and_test:
    jobs:
      - deps_api:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test_api:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - deps_api
      - deps_portal:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test_portal:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - deps_portal
