version: 2.1
jobs:
  deps_all:
    docker:
      # Use one of circleci's images packed with curl, actual language doesn't matter for this job.
      - image: circleci/golang:1.12
    steps:
      - run: sudo apt-get install jq
      - run: LATEST_CODACY_COVER_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
      - run: curl -Ls -o /coveragebin/codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_CODACY_COVER_VERSION}/codacy-coverage-reporter-linux"
      - run: chmod +x /coveragebin/codacy-coverage-reporter
      - save_cache:
          key: apydox-all-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /coveragebin
  deps_api:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/apydox/api
    steps:
      - checkout:
          path: ~/apydox
      - run: go get -v -t -d ./...
      - run: go get github.com/axw/gocov/gocov
      - run: go get github.com/AlekSi/gocov-xml
      - save_cache:
          key: apydox-api-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/apydox/api
            - "/go/pkg/mod"
  test_api:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/apydox/api
    steps:
      - restore_cache:
          keys:
            - apydox-api-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-api-v1-{{ .Branch }}-
            - apydox-api-v1-
      - restore_cache:
          keys:
            - apydox-all-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-all-v1-{{ .Branch }}-
            - apydox-all-v1-
      - run: gocov test -v ./... | gocov-xml > coverage.xml
      - run: /coveragebin/codacy-coverage-reporter report -l Go --force-language -r coverage.xml
  deps_portal:
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    working_directory: ~/apydox/portal
    steps:
      - checkout:
          path: ~/apydox
      - run: yarn
      - run: cp src/content.example.json src/content.json
      - save_cache:
          key: apydox-portal-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/apydox/portal
  test_portal:
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    working_directory: ~/apydox/portal
    steps:
      - restore_cache:
          keys: 
            - apydox-portal-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-portal-v1-{{ .Branch }}-
            - apydox-portal-v1-
      - restore_cache:
          keys:
            - apydox-all-v1-{{ .Branch }}-{{ .Revision }}
            - apydox-all-v1-{{ .Branch }}-
            - apydox-all-v1-
      - run: yarn test
      - run: /coveragebin/codacy-coverage-reporter report -l TypeScript --force-language -r coverage/cobertura-coverage.xml
workflows:
  version: 2
  deps_and_test:
    jobs:
      - deps_all:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master 
      - deps_api:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test_api:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - deps_api
            - deps_all
      - deps_portal:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test_portal:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - deps_portal
            - deps_all
